project_name: blue-team-go
builds:
  - id: tools
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    binary: "{{ .ProjectName }}"
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
